name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK 17 and cache Gradle
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # 3. Build using the official Gradle build action
      - name: Build debug APK
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.14'
          arguments: assembleDebug --stacktrace

      # 4. Upload the generated APK
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: media-output-tile-debug
          path: app/build/outputs/apk/debug/*.apk
